name: Build and Deploy to GKE

on:
  workflow_dispatch:  # Triggers when manually triggered from the GitHub Actions UI
    branches:
      - master
    inputs:
      tags:
        description: 'Docker Tag'
        required: true
        type: string

  pull_request:  # Triggers when a pull request is closed
    types: 
      - closed
    branches:
      - development
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ciao-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1-c     # Add your cluster zone here.
  DEPLOYMENT_NAME: ciao  # Add your deployment name here.
  IMAGE: myapp

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        sed -i -e 's/GITHUB_SHA/'"$GITHUB_SHA"'/' -e 's/PROJECT_ID/'"$PROJECT_ID"'/' ${{ github.workspace }}/.github/manifests/deployment.yaml
        kubectl apply -f ${{ github.workspace }}/.github/manifests/deployment.yaml